# Specify the base image. Here we use version 14 of node available from the Docker Hub.
FROM node:16-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY ./package.json /app

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . /app

# Expose the port the app runs on
EXPOSE 3000


# Command to run the application
CMD ["npm", "start"]

